### ISSUE TITLE
Use the new TypeVarTuple to implement a single Tensor type.

### ISSUE THREAD

**Issue by ruler501** [deepmind/tensor_annotations#12]
Using Unpack and TypeVarTuple from https://peps.python.org/pep-0646/#appendix-a-shape-typing-use-cases

You can make it work in older python versions by using the typing-extensions package that has backported the functionality all the way to python 3.7. (though you have to use `Unpack[TypeTuple]` instead of `*TypeTuple` since that required a grammar change).

I'd be glad to help with some of this if you wanted to point me at where to start.

**Comment by mrahtz** [comment]
We've actually deliberately decided not to use PEP 646 (yet), for compatibility reasons. There are two factors: a) concise syntax for PEP 646 is only available in Python 3.11 onwards, which not everyone can migrate to yet; and b) PEP 646 is (as of January 2022) only supported by Pyre and Pyright - not by Mypy or pytype, which are both popular.

Type checker support is the biggest thing - so once there is better support for PEP 646 in Mypy and pytype, we may revisit this question. Since I anticipate that taking a long time though - maybe ~years :( - for now I'll close this issue.
